#!/usr/bin/env python3
"""
train_omniaddress.py — Fine-tune T5-small on the OmniAddress corpus.

WHAT THIS IS: A tutorial for how seq2seq LLM fine-tuning works.
We're teaching T5 to map free-form English → subject.verb.object.tense.negator

Corpus: omni_phase1_corpus.jsonl  (300 pairs, generated by corpus1.py)
Output: ./omniaddress_model/       (HuggingFace format)

Run:  python3 train_omniaddress.py
GPU:  RTX 4060 (~3-5 min)
CPU:  will work, ~30-60 min

After training, the parser is available from omniaddress.py as auto_parse(text).
"""

import json
import os
import random
from pathlib import Path
from typing import List, Dict

# HuggingFace ecosystem — datasets handles the batching, transformers does the model
from transformers import (
    AutoTokenizer,
    T5ForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback,
)
from datasets import Dataset
import torch

# ── Config ────────────────────────────────────────────────────────────────────

CORPUS_PATH    = Path(os.environ.get("OMNI_CORPUS", "omni_phase1_corpus.jsonl"))  # default RICH v1 (frozen 69.2% baseline); override via OMNI_CORPUS env. Canon-training re-tested 2026-05-28 = wash vs rich+execution-canon, so canon stays an EXECUTION-layer map, not a training transform.
MODEL_NAME     = "google/flan-t5-base"  # 250M params — instruction-tuned, English-focused.
                                        # Replaces t5-small which leaked French tokens
                                        # (batterie, entrée, approche) on small-data fine-tunes.
OUTPUT_DIR     = Path(os.environ.get("OMNI_OUT", "omniaddress_model"))  # override via OMNI_OUT to keep the live model dir frozen during experiments
EVAL_SPLIT     = 0.20                # 20% held out (60 examples)
SEED           = 42

# Hyperparameters — tuned for a small dataset (~480 train examples)
# flan-t5-base is ~4x bigger than t5-small, so lower LR + smaller batch.
NUM_EPOCHS     = 60                  # Upper bound — early stopping will cut this short
BATCH_SIZE     = 8                   # flan-t5-base needs more VRAM than t5-small
LEARNING_RATE  = 1e-4                # Lower LR works better for instruction-tuned base
MAX_INPUT_LEN  = 96                  # English sentences in corpus are all short
MAX_TARGET_LEN = 24                  # OmniAddress is 5 dot-separated tokens, ~20 chars


# ── Step 1: Load corpus ───────────────────────────────────────────────────────

def load_corpus(path: Path) -> List[Dict]:
    pairs = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                pairs.append(json.loads(line))
    print(f"[corpus] Loaded {len(pairs)} pairs from {path.name}")
    return pairs


# ── Step 2: Train / eval split ────────────────────────────────────────────────
# Hold out 20% so we can measure real accuracy on unseen examples.

def split_corpus(pairs: List[Dict], eval_frac: float = 0.2, seed: int = 42):
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    n_eval     = int(len(shuffled) * eval_frac)
    eval_set   = shuffled[:n_eval]
    train_set  = shuffled[n_eval:]
    print(f"[split]  train={len(train_set)}  eval={len(eval_set)}")
    return train_set, eval_set


# ── Step 3: Tokenise ──────────────────────────────────────────────────────────
# T5 is "text-to-text" — every task is framed as string in, string out.
# We prefix inputs with "omniaddress: " to tell the model which task it's doing.
# The model learns: "omniaddress: The robot saw a chair" → "robot.detected.chair.now.true"

def tokenize_batch(examples: Dict, tokenizer) -> Dict:
    # Add task prefix to inputs
    inputs  = ["omniaddress: " + e for e in examples["english"]]
    targets = examples["omni"]

    # Tokenize inputs
    model_inputs = tokenizer(
        inputs,
        max_length=MAX_INPUT_LEN,
        truncation=True,
        padding=False,   # DataCollatorForSeq2Seq pads within each batch — more efficient
    )

    # Tokenize targets as labels (text_target= tells the tokenizer to use decoder vocab handling)
    labels = tokenizer(
        text_target=targets,
        max_length=MAX_TARGET_LEN,
        truncation=True,
        padding=False,
    )

    # "labels" is what the model is trained to predict
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


# ── Step 4: Evaluate on held-out set ─────────────────────────────────────────
# After training, run the model on each eval example and print predicted vs actual.
# Exact match is the key metric — the output format is deterministic.

def run_eval(model, tokenizer, eval_data: List[Dict], device) -> float:
    print("\n── Evaluation (held-out 20%) ─────────────────────────────────────────")
    model.eval()
    correct = 0

    for item in eval_data:
        # Tokenize the input the same way we did during training
        inp = tokenizer(
            "omniaddress: " + item["english"],
            return_tensors="pt",
            max_length=MAX_INPUT_LEN,
            truncation=True,
        ).to(device)

        with torch.no_grad():
            # generate() runs beam search / greedy decode to produce the output tokens
            out_ids = model.generate(**inp, max_new_tokens=MAX_TARGET_LEN, num_beams=4)

        pred = tokenizer.decode(out_ids[0], skip_special_tokens=True).strip()
        gold = item["omni"].strip()

        match = pred == gold
        if match:
            correct += 1
        status = "✓" if match else "✗"

        print(f"  {status}  pred: {pred:<42} gold: {gold}")

    pct = 100.0 * correct / len(eval_data)
    print(f"\n  Exact match: {correct}/{len(eval_data)}  ({pct:.1f}%)")
    return pct


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 64)
    print("  OmniAddress Fine-tune  —  T5-small")
    print("=" * 64)

    # Device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[device] {device}"
          + (f"  ({torch.cuda.get_device_name(0)})" if torch.cuda.is_available() else ""))

    # Load and split corpus
    pairs               = load_corpus(CORPUS_PATH)
    train_pairs, eval_pairs = split_corpus(pairs, EVAL_SPLIT, SEED)

    # Convert to HuggingFace Dataset (expects list-of-dicts or dict-of-lists)
    train_ds = Dataset.from_list(train_pairs)
    eval_ds  = Dataset.from_list(eval_pairs)

    # Load tokenizer and model
    print(f"\n[model] Loading {MODEL_NAME}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model     = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)
    model.to(device)
    print(f"[model] {model.num_parameters():,} parameters")

    # Tokenise both splits
    # batched=True processes rows in chunks — much faster than row-by-row
    # remove_columns drops the original text columns (model only needs token IDs)
    print("\n[tokenise] Processing...")
    train_tok = train_ds.map(
        lambda x: tokenize_batch(x, tokenizer),
        batched=True,
        remove_columns=train_ds.column_names,
    )
    eval_tok = eval_ds.map(
        lambda x: tokenize_batch(x, tokenizer),
        batched=True,
        remove_columns=eval_ds.column_names,
    )

    # DataCollator pads each batch to its own max length (not globally)
    # This is the standard efficient approach for seq2seq
    collator = DataCollatorForSeq2Seq(tokenizer, model=model, padding=True)

    # Training configuration
    # fp16=True: mixed precision — ~2x faster on RTX 4060 with no accuracy loss
    # eval_strategy + save_strategy both "epoch" + load_best_model_at_end:
    #   saves a checkpoint after every epoch, loads the best one at the end
    ckpt_dir = str(OUTPUT_DIR / "checkpoints")
    args = Seq2SeqTrainingArguments(
        output_dir                  = ckpt_dir,
        num_train_epochs            = NUM_EPOCHS,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = BATCH_SIZE,
        learning_rate               = LEARNING_RATE,
        warmup_steps                = 40,           # Gradual LR ramp helps small datasets
        weight_decay                = 0.01,         # Mild L2 regularisation
        logging_steps               = 10,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        load_best_model_at_end      = True,
        metric_for_best_model       = "eval_loss",  # Checkpoint selection criterion
        predict_with_generate       = True,         # Use generate() during eval, not greedy logits
        # flan-t5 has activation values that overflow fp16, producing NaN losses.
        # bf16 has the same dynamic range as fp32 — no overflow — and the RTX 4060
        # supports it natively. Same speed as fp16 in practice.
        bf16                        = torch.cuda.is_available(),
        report_to                   = "none",       # Disable wandb / tensorboard
        seed                        = SEED,
        save_total_limit            = 2,            # Keep only best + last. Each ckpt is ~2.8G (model+optimizer);
                                                    # 15 filled the disk and crashed the run on 2026-05-28.
    )

    trainer = Seq2SeqTrainer(
        model            = model,
        args             = args,
        train_dataset    = train_tok,
        eval_dataset     = eval_tok,
        processing_class = tokenizer,   # transformers 5.x renamed tokenizer= to processing_class=
        data_collator    = collator,
        # Stop when eval_loss stops improving — prevents loading a late overfit checkpoint.
        # patience=6: stop if no improvement for 6 consecutive evals (epochs).
        callbacks        = [EarlyStoppingCallback(early_stopping_patience=6)],
    )

    # Train
    print(f"\n[train] Starting — {NUM_EPOCHS} epochs, batch={BATCH_SIZE}, lr={LEARNING_RATE}")
    trainer.train()

    # Save the final model in HuggingFace format
    # This is what omniaddress.py loads with from_pretrained(OUTPUT_DIR)
    OUTPUT_DIR.mkdir(exist_ok=True)
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"\n[save] Model written to {OUTPUT_DIR}/")

    # Run held-out evaluation and print results
    run_eval(model, tokenizer, eval_pairs, device)

    print("\n[done] Fine-tune complete.")
    print(f"       In omniaddress.py, auto_parse() will load from '{OUTPUT_DIR}/'")


if __name__ == "__main__":
    main()
